# spring:
#   data:
#     mongodb:
#       host: localhost
#       port: 27018
#       database: classe_db
#       username: m1Info
#       password: m1Info
#       authentication-database: admin

# # server:
# #   servlet:
# #     context-path: /api
# #   port: 8010

# grpc:
#   server:
#     port: 8012

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: classe_db
      username: m1Info
      password: m1Info
      authentication-database: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # datasource:
  #   url: jdbc:mysql://localhost:3306/etudiant_db
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver

# Optionnel : pour REST
# server:
#   servlet:
#     context-path: /api
#   port: 8010

grpc:
  server:
    port: 8012
