server:
  port: 8222

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://localhost:9098/realms/micro-services"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: course-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/courses/**
            - id: assessment-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/assessments/**
            - id: lesson-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/lessons/**
            - id: lesson-pdf-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/cours/**
            - id: module-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/modules/**
            - id: admin-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/admins/**
            - id: professor-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/professors/**
            - id: student-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/students/**
            - id: notification-service
              uri: lb:http://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**
            - id: ai-deepSeek
              uri: lb:http://AI-DEEPSEEK
              predicates:
                - Path=/api/v1/deepSeek/**
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=500,expireAfterWrite=10m
