server:
  port: 8222

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://localhost:9098/realms/micro-services"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: classe-service
              uri: lb:http://CLASSE-SERVICE
              predicates:
                - Path=/api/v1/classes/**
            - id: etudiant-service
              uri: lb:http://ETUDIANT-SERVICE
              predicates:
                - Path=/api/v1/students/**
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=500,expireAfterWrite=10m
