package com.webService.etudiant.model;

public enum DEPARTEMENT {
    INFORMATIQUE,
    ELECTRONIQUE,
    TELECOMMUNICATION,
    MECANIQUE,
    CIVIL,
    BIOLOGIE,
    CHIMIE,
    PHYSIQUE,
    MATHEMATIQUES,
    SCIENCES_DE_LA_NATURE,
    SCIENCES_DE_LA_VIE,
    SCIENCES_DE_LA_TERRAIN,
    SCIENCES_SOCIALES,
    SCIENCES_HUMAINES
}
